
package sk11;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "SdmService", targetNamespace = "http://monitel.com/CK11/Services/SDM")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SdmService {


    /**
     * 
     * @param request
     * @return
     *     returns sk11.GetInformationModelsResponse2
     * @throws SdmServiceGetInformationModelsInformationModelsFaultMessageFaultMessage
     */
    @WebMethod(operationName = "GetInformationModels", action = "http://monitel.com/CK11/Services/SDM/SdmService/GetInformationModels")
    @WebResult(name = "GetInformationModelsResult", targetNamespace = "http://monitel.com/CK11/Services/SDM")
    @RequestWrapper(localName = "GetInformationModels", targetNamespace = "http://monitel.com/CK11/Services/SDM", className = "sk11.GetInformationModels")
    @ResponseWrapper(localName = "GetInformationModelsResponse", targetNamespace = "http://monitel.com/CK11/Services/SDM", className = "sk11.GetInformationModelsResponse")
    public GetInformationModelsResponse2 getInformationModels(
        @WebParam(name = "request", targetNamespace = "http://monitel.com/CK11/Services/SDM")
        GetInformationModelsRequest request)
        throws SdmServiceGetInformationModelsInformationModelsFaultMessageFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns sk11.GetModelVersionsResponse2
     * @throws SdmServiceGetModelVersionsModelVersionsFaultMessageFaultMessage
     */
    @WebMethod(operationName = "GetModelVersions", action = "http://monitel.com/CK11/Services/SDM/SdmService/GetModelVersions")
    @WebResult(name = "GetModelVersionsResult", targetNamespace = "http://monitel.com/CK11/Services/SDM")
    @RequestWrapper(localName = "GetModelVersions", targetNamespace = "http://monitel.com/CK11/Services/SDM", className = "sk11.GetModelVersions")
    @ResponseWrapper(localName = "GetModelVersionsResponse", targetNamespace = "http://monitel.com/CK11/Services/SDM", className = "sk11.GetModelVersionsResponse")
    public GetModelVersionsResponse2 getModelVersions(
        @WebParam(name = "request", targetNamespace = "http://monitel.com/CK11/Services/SDM")
        GetModelVersionsRequest request)
        throws SdmServiceGetModelVersionsModelVersionsFaultMessageFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns sk11.GetModelVersionsDifferenceResponse2
     * @throws SdmServiceGetModelVersionsDifferenceModelVersionsDifferenceFaultMessageFaultMessage
     */
    @WebMethod(operationName = "GetModelVersionsDifference", action = "http://monitel.com/CK11/Services/SDM/SdmService/GetModelVersionsDifference")
    @WebResult(name = "GetModelVersionsDifferenceResult", targetNamespace = "http://monitel.com/CK11/Services/SDM")
    @RequestWrapper(localName = "GetModelVersionsDifference", targetNamespace = "http://monitel.com/CK11/Services/SDM", className = "sk11.GetModelVersionsDifference")
    @ResponseWrapper(localName = "GetModelVersionsDifferenceResponse", targetNamespace = "http://monitel.com/CK11/Services/SDM", className = "sk11.GetModelVersionsDifferenceResponse")
    public GetModelVersionsDifferenceResponse2 getModelVersionsDifference(
        @WebParam(name = "request", targetNamespace = "http://monitel.com/CK11/Services/SDM")
        GetModelVersionsDifferenceRequest request)
        throws SdmServiceGetModelVersionsDifferenceModelVersionsDifferenceFaultMessageFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns sk11.GetActualModelVersionResponse2
     * @throws SdmServiceGetActualModelVersionGetActualModelVersionFaultMessageFaultMessage
     */
    @WebMethod(operationName = "GetActualModelVersion", action = "http://monitel.com/CK11/Services/SDM/SdmService/GetActualModelVersion")
    @WebResult(name = "GetActualModelVersionResult", targetNamespace = "http://monitel.com/CK11/Services/SDM")
    @RequestWrapper(localName = "GetActualModelVersion", targetNamespace = "http://monitel.com/CK11/Services/SDM", className = "sk11.GetActualModelVersion")
    @ResponseWrapper(localName = "GetActualModelVersionResponse", targetNamespace = "http://monitel.com/CK11/Services/SDM", className = "sk11.GetActualModelVersionResponse")
    public GetActualModelVersionResponse2 getActualModelVersion(
        @WebParam(name = "request", targetNamespace = "http://monitel.com/CK11/Services/SDM")
        GetActualModelVersionRequest request)
        throws SdmServiceGetActualModelVersionGetActualModelVersionFaultMessageFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns sk11.CreateModelVersionResponse2
     * @throws SdmServiceCreateModelVersionModelVersionsFaultMessageFaultMessage
     */
    @WebMethod(operationName = "CreateModelVersion", action = "http://monitel.com/CK11/Services/SDM/SdmService/CreateModelVersion")
    @WebResult(name = "CreateModelVersionResult", targetNamespace = "http://monitel.com/CK11/Services/SDM")
    @RequestWrapper(localName = "CreateModelVersion", targetNamespace = "http://monitel.com/CK11/Services/SDM", className = "sk11.CreateModelVersion")
    @ResponseWrapper(localName = "CreateModelVersionResponse", targetNamespace = "http://monitel.com/CK11/Services/SDM", className = "sk11.CreateModelVersionResponse")
    public CreateModelVersionResponse2 createModelVersion(
        @WebParam(name = "request", targetNamespace = "http://monitel.com/CK11/Services/SDM")
        CreateModelVersionRequest request)
        throws SdmServiceCreateModelVersionModelVersionsFaultMessageFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns sk11.ChangeModelVersionStateResponse2
     * @throws SdmServiceChangeModelVersionStateChangeModelVersionStatetMessageFaultMessage
     */
    @WebMethod(operationName = "ChangeModelVersionState", action = "http://monitel.com/CK11/Services/SDM/SdmService/ChangeModelVersionState")
    @WebResult(name = "ChangeModelVersionStateResult", targetNamespace = "http://monitel.com/CK11/Services/SDM")
    @RequestWrapper(localName = "ChangeModelVersionState", targetNamespace = "http://monitel.com/CK11/Services/SDM", className = "sk11.ChangeModelVersionState")
    @ResponseWrapper(localName = "ChangeModelVersionStateResponse", targetNamespace = "http://monitel.com/CK11/Services/SDM", className = "sk11.ChangeModelVersionStateResponse")
    public ChangeModelVersionStateResponse2 changeModelVersionState(
        @WebParam(name = "request", targetNamespace = "http://monitel.com/CK11/Services/SDM")
        ChangeModelVersionStateRequest request)
        throws SdmServiceChangeModelVersionStateChangeModelVersionStatetMessageFaultMessage
    ;

    /**
     * 
     * @param req
     * @return
     *     returns sk11.GetObjectsResponse2
     * @throws SdmServiceGetObjectsObjectsFaultMessageFaultMessage
     */
    @WebMethod(operationName = "GetObjects", action = "http://monitel.com/CK11/Services/SDM/SdmService/GetObjects")
    @WebResult(name = "GetObjectsResult", targetNamespace = "http://monitel.com/CK11/Services/SDM")
    @RequestWrapper(localName = "GetObjects", targetNamespace = "http://monitel.com/CK11/Services/SDM", className = "sk11.GetObjects")
    @ResponseWrapper(localName = "GetObjectsResponse", targetNamespace = "http://monitel.com/CK11/Services/SDM", className = "sk11.GetObjectsResponse")
    public GetObjectsResponse2 getObjects(
        @WebParam(name = "req", targetNamespace = "http://monitel.com/CK11/Services/SDM")
        GetObjectsRequest req)
        throws SdmServiceGetObjectsObjectsFaultMessageFaultMessage
    ;

    /**
     * 
     * @param req
     * @return
     *     returns sk11.DeleteModelVersionResponse2
     * @throws SdmServiceDeleteModelVersionDeleteModelVersionFaultMessageFaultMessage
     */
    @WebMethod(operationName = "DeleteModelVersion", action = "http://monitel.com/CK11/Services/SDM/SdmService/DeleteModelVersion")
    @WebResult(name = "DeleteModelVersionResult", targetNamespace = "http://monitel.com/CK11/Services/SDM")
    @RequestWrapper(localName = "DeleteModelVersion", targetNamespace = "http://monitel.com/CK11/Services/SDM", className = "sk11.DeleteModelVersion")
    @ResponseWrapper(localName = "DeleteModelVersionResponse", targetNamespace = "http://monitel.com/CK11/Services/SDM", className = "sk11.DeleteModelVersionResponse")
    public DeleteModelVersionResponse2 deleteModelVersion(
        @WebParam(name = "req", targetNamespace = "http://monitel.com/CK11/Services/SDM")
        DeleteModelVersionRequest req)
        throws SdmServiceDeleteModelVersionDeleteModelVersionFaultMessageFaultMessage
    ;

    /**
     * 
     * @param req
     * @return
     *     returns sk11.GetValidationResultResponse2
     * @throws SdmServiceGetValidationResultValidationResultFaultMessageFaultMessage
     */
    @WebMethod(operationName = "GetValidationResult", action = "http://monitel.com/CK11/Services/SDM/SdmService/GetValidationResult")
    @WebResult(name = "GetValidationResultResult", targetNamespace = "http://monitel.com/CK11/Services/SDM")
    @RequestWrapper(localName = "GetValidationResult", targetNamespace = "http://monitel.com/CK11/Services/SDM", className = "sk11.GetValidationResult")
    @ResponseWrapper(localName = "GetValidationResultResponse", targetNamespace = "http://monitel.com/CK11/Services/SDM", className = "sk11.GetValidationResultResponse")
    public GetValidationResultResponse2 getValidationResult(
        @WebParam(name = "req", targetNamespace = "http://monitel.com/CK11/Services/SDM")
        GetValidationResultRequest req)
        throws SdmServiceGetValidationResultValidationResultFaultMessageFaultMessage
    ;

    /**
     * 
     * @param req
     * @return
     *     returns sk11.ChangeObjectsResponse2
     * @throws SdmServiceChangeObjectsChangeObjectsMessageFaultMessage
     */
    @WebMethod(operationName = "ChangeObjects", action = "http://monitel.com/CK11/Services/SDM/SdmService/ChangeObjects")
    @WebResult(name = "ChangeObjectsResult", targetNamespace = "http://monitel.com/CK11/Services/SDM")
    @RequestWrapper(localName = "ChangeObjects", targetNamespace = "http://monitel.com/CK11/Services/SDM", className = "sk11.ChangeObjects")
    @ResponseWrapper(localName = "ChangeObjectsResponse", targetNamespace = "http://monitel.com/CK11/Services/SDM", className = "sk11.ChangeObjectsResponse")
    public ChangeObjectsResponse2 changeObjects(
        @WebParam(name = "req", targetNamespace = "http://monitel.com/CK11/Services/SDM")
        ChangeObjectsRequest req)
        throws SdmServiceChangeObjectsChangeObjectsMessageFaultMessage
    ;

    /**
     * 
     * @param req
     * @return
     *     returns sk11.GetProfilesResponse2
     * @throws SdmServiceGetProfilesGetProfilesMessageFaultMessage
     */
    @WebMethod(operationName = "GetProfiles", action = "http://monitel.com/CK11/Services/SDM/SdmService/GetProfiles")
    @WebResult(name = "GetProfilesResult", targetNamespace = "http://monitel.com/CK11/Services/SDM")
    @RequestWrapper(localName = "GetProfiles", targetNamespace = "http://monitel.com/CK11/Services/SDM", className = "sk11.GetProfiles")
    @ResponseWrapper(localName = "GetProfilesResponse", targetNamespace = "http://monitel.com/CK11/Services/SDM", className = "sk11.GetProfilesResponse")
    public GetProfilesResponse2 getProfiles(
        @WebParam(name = "req", targetNamespace = "http://monitel.com/CK11/Services/SDM")
        GetProfilesRequest req)
        throws SdmServiceGetProfilesGetProfilesMessageFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns sk11.GetProfilesSetResponse2
     * @throws SdmServiceGetProfilesSetGetProfilesSetMessageFaultMessage
     */
    @WebMethod(operationName = "GetProfilesSet", action = "http://monitel.com/CK11/Services/SDM/SdmService/GetProfilesSet")
    @WebResult(name = "GetProfilesSetResult", targetNamespace = "http://monitel.com/CK11/Services/SDM")
    @RequestWrapper(localName = "GetProfilesSet", targetNamespace = "http://monitel.com/CK11/Services/SDM", className = "sk11.GetProfilesSet")
    @ResponseWrapper(localName = "GetProfilesSetResponse", targetNamespace = "http://monitel.com/CK11/Services/SDM", className = "sk11.GetProfilesSetResponse")
    public GetProfilesSetResponse2 getProfilesSet(
        @WebParam(name = "request", targetNamespace = "http://monitel.com/CK11/Services/SDM")
        GetProfilesSetRequest request)
        throws SdmServiceGetProfilesSetGetProfilesSetMessageFaultMessage
    ;

    /**
     * 
     * @param req
     * @return
     *     returns sk11.GetUnaccountedStocksResponse2
     * @throws SdmServiceGetUnaccountedStocksGetUnaccountedStocksMessageFaultMessage
     */
    @WebMethod(operationName = "GetUnaccountedStocks", action = "http://monitel.com/CK11/Services/SDM/SdmService/GetUnaccountedStocks")
    @WebResult(name = "GetUnaccountedStocksResult", targetNamespace = "http://monitel.com/CK11/Services/SDM")
    @RequestWrapper(localName = "GetUnaccountedStocks", targetNamespace = "http://monitel.com/CK11/Services/SDM", className = "sk11.GetUnaccountedStocks")
    @ResponseWrapper(localName = "GetUnaccountedStocksResponse", targetNamespace = "http://monitel.com/CK11/Services/SDM", className = "sk11.GetUnaccountedStocksResponse")
    public GetUnaccountedStocksResponse2 getUnaccountedStocks(
        @WebParam(name = "req", targetNamespace = "http://monitel.com/CK11/Services/SDM")
        GetUnaccountedStocksRequest req)
        throws SdmServiceGetUnaccountedStocksGetUnaccountedStocksMessageFaultMessage
    ;

}
