
package sk11;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "SdmService", targetNamespace = "http://monitel.com/CK11/Services/SDM", wsdlLocation = "file:/C:/Repos/mygithub/test/soap-client-try/src/main/resources/wsdl/SdmService.wsdl")
public class SdmService_Service
    extends Service
{

    private final static URL SDMSERVICE_WSDL_LOCATION;
    private final static WebServiceException SDMSERVICE_EXCEPTION;
    private final static QName SDMSERVICE_QNAME = new QName("http://monitel.com/CK11/Services/SDM", "SdmService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Repos/mygithub/test/soap-client-try/src/main/resources/wsdl/SdmService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SDMSERVICE_WSDL_LOCATION = url;
        SDMSERVICE_EXCEPTION = e;
    }

    public SdmService_Service() {
        super(__getWsdlLocation(), SDMSERVICE_QNAME);
    }

    public SdmService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SDMSERVICE_QNAME, features);
    }

    public SdmService_Service(URL wsdlLocation) {
        super(wsdlLocation, SDMSERVICE_QNAME);
    }

    public SdmService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SDMSERVICE_QNAME, features);
    }

    public SdmService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SdmService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SdmService
     */
    @WebEndpoint(name = "SdmService")
    public SdmService getSdmService() {
        return super.getPort(new QName("http://monitel.com/CK11/Services/SDM", "SdmService"), SdmService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SdmService
     */
    @WebEndpoint(name = "SdmService")
    public SdmService getSdmService(WebServiceFeature... features) {
        return super.getPort(new QName("http://monitel.com/CK11/Services/SDM", "SdmService"), SdmService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SDMSERVICE_EXCEPTION!= null) {
            throw SDMSERVICE_EXCEPTION;
        }
        return SDMSERVICE_WSDL_LOCATION;
    }

}
